module.exports = {
  apps: [
    {
      name: 'automation-scheduler',
      script: './scheduler/index.js',
      interpreter: 'node',
      interpreter_args: '--experimental-vm-modules',
      cwd: '/Users/Rascal/work/automation',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
        MODE: 'prod',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/pm2-scheduler-error.log',
      out_file: './logs/pm2-scheduler-out.log',
      merge_logs: true,
    },
    {
      name: 'bridge-server',
      script: './bridge/server.js',
      interpreter: 'node',
      interpreter_args: '--experimental-vm-modules',
      cwd: '/Users/Rascal/work/automation',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        MODE: 'prod',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/pm2-bridge-error.log',
      out_file: './logs/pm2-bridge-out.log',
      merge_logs: true,
    },
    {
      name: 'brave-watchdog',
      script: './x/brave-watchdog.js',
      interpreter: 'node',
      interpreter_args: '--experimental-vm-modules',
      cwd: '/Users/Rascal/work/automation',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '128M',
      restart_delay: 10000,
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/pm2-watchdog-error.log',
      out_file: './logs/pm2-watchdog-out.log',
      merge_logs: true,
    },
  ],
};
